#robot:

  #Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
        
  # Joint trajectory controller
  position_trajectory_controller:
    type: "effort_controllers/JointTrajectoryController"
#    type: "kuka_control/JointTrajectoryController"
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
    gains:
      joint_a1:
        p: 10000
        i: 10
        d: 100
        i_clamp_max: 0.1
        i_clamp_min: -0.1
      joint_a2:
        p: 10000
        i: 10
        d: 200
        i_clamp_max: 0.1
        i_clamp_min: -0.1
      joint_a3:
        p: 10000
        i: 10
        d: 200
        i_clamp_max: 0.1
        i_clamp_min: -0.1
      joint_a4:
        p: 500
        i: 1
        d: 5
        i_clamp_max: 0.1
        i_clamp_min: -0.1
      joint_a5:
        p: 20
        i: 5
        d: 1
        i_clamp_max: 0.1
        i_clamp_min: -0.1
      joint_a6:
        p: 10
        i: 1
        d: 0.1
        i_clamp_max: 0.1
        i_clamp_min: -0.1
    root_link: base_link
    tip_link: tool0

    state_publish_rate: 50 # Defaults to 50
    action_monitor_rate: 20 # Defaults to 20

#  # Joint group position controller
#  joint_group_position_controller:
#    type: effort_controllers/JointGroupPositionController
#    joints:
#      - joint_a1
#      - joint_a2
#      - joint_a3
#      - joint_a4
#      - joint_a5
#      - joint_a6

