elfin:

  #Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
        
  # Joint trajectory controller
  position_trajectory_controller:
#    type: "effort_controllers/JointTrajectoryController"
    type: "kuka_control/JointTrajectoryController"
    joints:
      - elfin_joint1
      - elfin_joint2
      - elfin_joint3
      - elfin_joint4
      - elfin_joint5
      - elfin_joint6
    gains:
      elfin_joint1:
        p: 10000
        i: 10
        d: 100
        i_clamp_max: 0.1
        i_clamp_min: -0.1
      elfin_joint2:
        p: 10000
        i: 10
        d: 200
        i_clamp_max: 0.1
        i_clamp_min: -0.1
      elfin_joint3:
        p: 10000
        i: 10
        d: 200
        i_clamp_max: 0.1
        i_clamp_min: -0.1
      elfin_joint4:
        p: 500
        i: 1
        d: 5
        i_clamp_max: 0.1
        i_clamp_min: -0.1
      elfin_joint5:
        p: 500
        i: 1
        d: 5
        i_clamp_max: 0.1
        i_clamp_min: -0.1
      elfin_joint6:
        p: 10
        i: 1
        d: 0.1
        i_clamp_max: 0.1
        i_clamp_min: -0.1
    root_link: elfin_base
    tip_link: elfin_link6

    state_publish_rate: 50 # Defaults to 50
    action_monitor_rate: 20 # Defaults to 20

